### ISSUE TITLE
Lua error when polygon count is less than 321

### ISSUE THREAD

**Issue by pfhore-github** [Hopper262/Vasara#1]
Triggers.init() cause error at line 86 when I tried to enter Vasara on map with <321 polygons

[string "Solo Lua"]:86: attempt to index field '?' (a nil value) (D:\a\alephone\alephone\Source_Files\Lua\lua_script.cpp:1201)
[string "Solo Lua"]:1028: attempt to index field '_v' (a nil value) (D:\a\alephone\alephone\Source_Files\Lua\lua_script.cpp:1201)
[string "Solo Lua"]:1207: attempt to index field '_v' (a nil value) (D:\a\alephone\alephone\Source_Files\Lua\lua_script.cpp:1201)
[string "HUD Lua"]:143: Vasara HUD requires Vasara Script (D:\a\alephone\alephone\Source_Files\Lua\lua_script.cpp:1201)
[string "Solo Lua"]:1028: attempt to index field '_v' (a nil value) (D:\a\alephone\alephone\Source_Files\Lua\lua_script.cpp:1201)

**Comment by Hopper262** [comment]
Thank you for the report! This should be fixed now in version 1.1.1.
